### ISSUE TITLE
Anvil not working

### ISSUE THREAD

**Issue by AntonPPDS** [GameModsBR/PowerNukkit#222]
The following issues has been found and are related:
- [x] #224 Anvil don't merge enchanted items correctly
- [x] #222 The level is charged twice when operating an anvil
- [x] #226 Wrong level cost calculation
- [x] #225 If a crafting transaction fails the items are destroyed
- [ ] #223 If a transaction fails, you can close the main player inventory
- [x] #228 The enchantment order mismatches the client and makes the transaction fail

### Expected Behavior
Item renamed/combined succesfully.

### Actual Behavior
Item disappeared.

### Steps to Reproduce
1. Put item
2. Change its name
3. Try to take the result. It will disappear including original item

### Used version
https://github.com/GameModsBR/PowerNukkit/commit/cee54afe1256867e957747026b7ec959d4102b32

**Comment by Htepple** [comment]
its because lootmc - trash :(

**Comment by AntonPPDS** [comment]
@Htepple May I ask you to leave our feud outside this place? This is a public contribution and nothing more

**Comment by Htepple** [comment]
> @Htepple May I ask you to leave our feud outside this place? This is a public contribution and nothing more

nope :0

**Comment by AntonPPDS** [comment]
[This](https://github.com/GameModsBR/PowerNukkit/blob/d9f33805857926e094f24391b1621b165a7f3584/src/main/java/cn/nukkit/Player.java#L2825) may be the reason of that. Client sends enchant event for anvil too, before the transaction, so it tries to take experience twice. If player has not neededExp*2, transaction will fail

**Comment by joserobjr** [comment]
Confirmed only when attempting to upgrade enchantments:
https://youtu.be/TkuRsl0OUkM

**Comment by joserobjr** [comment]
I could not reproduce exactly how you said but I fixed a related issue at #224 

Can you check if this build fixes your issue?
https://github.com/GameModsBR/PowerNukkit/suites/653386798/artifacts/5646437

It was generated from this action:
https://github.com/GameModsBR/PowerNukkit/runs/644779077

**Comment by joserobjr** [comment]
> [This](https://github.com/GameModsBR/PowerNukkit/blob/d9f33805857926e094f24391b1621b165a7f3584/src/main/java/cn/nukkit/Player.java#L2825) may be the reason of that. Client sends enchant event for anvil too, before the transaction, so it tries to take experience twice (event+transaction). If player has not neededExp*2, transaction will fail

I finally got your point, it's charging the double of the experience, so the transaction fails and it destroys the items.
https://youtu.be/nmS8wUbIw14

I'm also going to open an other issue to make the crafting transaction safer and do a nice rollback instead of destroying everything.

**Comment by Htepple** [comment]
not working :(

**Comment by joserobjr** [comment]
@Htepple @AntonPPDS Hello guys, can you check if this build fixes the issues?
https://github.com/GameModsBR/PowerNukkit/suites/660169343/artifacts/5800168

It was generated from:
https://github.com/GameModsBR/PowerNukkit/runs/651783174

The source is in this branch:
https://github.com/GameModsBR/PowerNukkit/commits/snapshot/v1.2.0.x

**Comment by AntonPPDS** [comment]
@joserobjr  https://github.com/GameModsBR/PowerNukkit/commit/ef4455dbfd21b3c72f385dca203e34f31e8aca8b#commitcomment-38999495

**Comment by joserobjr** [comment]
@AntonPPDS Which items and enchantments have you used? I could not reproduce anymore.

**Comment by AntonPPDS** [comment]
@joserobjr I've tried to combine two identical diamond pickaxes with Fortune II enchantment

**Comment by Htepple** [comment]
> @joserobjr I've tried to combine two identical diamond pickaxes with Fortune II enchantment (D.Pickaxe [Fortune II] + D.Pickaxe [Fortune II])

maybe you will use lastest build? it doesn't work

**Comment by Htepple** [comment]
![Minecraft Screenshot 2020 05 07 - 23 58 37 45](https://user-images.githubusercontent.com/34367447/81344049-bc909780-90be-11ea-98f0-e5004bf07eeb.png)
![Minecraft Screenshot 2020 05 08 - 00 01 32 99](https://user-images.githubusercontent.com/34367447/81344252-185b2080-90bf-11ea-8184-dc6d7ba93ff6.png)

this is fortune 3, maked with anvil :0

**Comment by joserobjr** [comment]
Thank you for the answers. I tried with D.Pickaxe [Fortune II] + D.Pickaxe [Fortune II] and it was successful and the level cost matched what was calculated by the client.

https://www.youtube.com/watch?v=IBwJE0ROwgM

Can you check if the issue still happens with the latest release?
https://github.com/GameModsBR/PowerNukkit/releases/tag/v1.2.0.1-PN

**Comment by AntonPPDS** [comment]
@joserobjr My bad, everything works fine

**Comment by joserobjr** [comment]
No problem, nice to know that it's fixed. Thank you for your contributions 😁👍

**Comment by AntonPPDS** [comment]
@joserobjr Seems that there are still some issues. Try to combine two items (i.e. Diamond Leggins)[Thorns II] together. Works in creative, but not in survival.

**Comment by AntonPPDS** [comment]
This is not an anvil issue, move to https://github.com/GameModsBR/PowerNukkit/issues/237

**Comment by AntonPPDS** [comment]
@joserobjr There are still wrong enchantment order issue. Not matches client side.
![image](https://user-images.githubusercontent.com/60366294/81396384-06fd2d00-912e-11ea-9056-70297ed3cbff.png)
![image](https://user-images.githubusercontent.com/60366294/81396422-167c7600-912e-11ea-918d-28afd18435d3.png)
![image](https://user-images.githubusercontent.com/60366294/81396477-25fbbf00-912e-11ea-8b62-4644fde0ecbb.png)
