### ISSUE TITLE
List of known bugs caused by the protocol change to 1.16.0

### ISSUE THREAD

**Issue by RORIdev** [GameModsBR/PowerNukkit#295]
Here is described all the known bugs which are caused by #293.
---
- [x] Creative Menu doesn't show items with negative ids/have damage values. Eg. `log:1`
- [x] Using Hoe on grass makes no sound - Assigned @LoboMetalurgico (#297)
- [x] Using Shovel on grass makes no sound - Assigned @LoboMetalurgico (#297)
- [x] Walls won't connect - Assigned: @joserobjr
- [x] Stems won't connect - Assigned: @joserobjr
- [x] Picking walls in creative (middle mouse button) gets an incorrect wall which get stuck in the inventory - Assigned: @joserobjr
- [x] Walls not connecting to trapdoors above them - Assigned: @joserobjr
- [x] Once a wall connect to an other wall, it won't disconnect when the other wall is broken - Assigned: @joserobjr
- [x] Walls metadata is corrupting after a save-load cycle - Assigned: @joserobjr
- [x] Inventory bug https://youtu.be/T22TmwYGH64
- [x] ~~Scoreboard packets need to be updated https://github.com/NukkitX/Nukkit/issues/1518~~ (Plugin related, no scoreboard packet is defined in this Nukkit version)
- [x] ~~You can't see other player's skins https://github.com/NukkitX/Nukkit/issues/1519~~ (Could not reproduce)
- [x] ~~Survival mode acting like adventure mode in the client view https://github.com/NukkitX/Nukkit/issues/1516 - https://www.youtube.com/watch?v=RtgNEhLn7ks~~ (Could not reproduce, plugin related?)
- [x] RakNet memory seems to be leaking - #312 #301 
- [x] ~~Review the enchanting table - https://github.com/GameModsBR/PowerNukkit/issues/295#issuecomment-651947971~~ (solved by NukkitX)
---
Block state notes:
* `minecraft:jigsaw` now has `rotation` alongside with `facing` (why? no idea)
* `minecraft:cobblestone_wall` now have: `wall_connection_type_east=none;wall_post_bit=0;wall_connection_type_south=none;wall_connection_type_west=none;wall_connection_type_north`
* `minecraft:melon_stem` and `minecraft:pumpkin_stem` now have `facing_direction`
---
Enchanting table (packets):
```java
0 = {InventoryTransactionPacket@6109} "InventoryTransactionPacket(transactionType=0, actions=[NetworkInventoryAction(sourceType=99999, windowId=-15, unknown=0, inventorySlot=0, oldItem=Item Air (0:0)x0, newItem=Item Diamond Chestplate (311:0)x1, stackNetworkId=0), NetworkInventoryAction(sourceType=99999, windowId=-17, unknown=0, inventorySlot=0, oldItem=Item Diamond Chestplate (311:0)x1 tags:0x0A0000090400656E63680A010000000203006C766C0100020200696400000000, newItem=Item Air (0:0)x0, stackNetworkId=0), NetworkInventoryAction(sourceType=0, windowId=124, unknown=0, inventorySlot=14, oldItem=Item Diamond Chestplate (311:0)x1, newItem=Item Diamond Chestplate (311:0)x1 tags:0x0A0000090400656E63680A010000000203006C766C0100020200696400000000, stackNetworkId=0)], transactionData=null, hasNetworkIds=false, legacyRequestId=0, isCraftingPart=false)"
1 = {PlayerActionPacket@6187} "PlayerActionPacket(entityId=8, action=20, x=0, y=0, z=0, face=1229200038)"
2 = {EntityEventPacket@6188} "EntityEventPacket(eid=8, event=34, data=-1)"
3 = {InventoryTransactionPacket@6189} "InventoryTransactionPacket(transactionType=0, actions=[NetworkInventoryAction(sourceType=99999, windowId=-16, unknown=0, inventorySlot=0, oldItem=Item Air (0:0)x0, newItem=Item Lapis Lazuli (351:4)x1, stackNetworkId=0), NetworkInventoryAction(sourceType=0, windowId=124, unknown=0, inventorySlot=15, oldItem=Item Lapis Lazuli (351:4)x1, newItem=Item Air (0:0)x0, stackNetworkId=0)], transactionData=null, hasNetworkIds=false, legacyRequestId=0, isCraftingPart=false)"
```

**Comment by soturi1991** [comment]
Ne blocks mit Work.

**Comment by Htepple** [comment]
> New blocks not Work.

not implemented yet

**Comment by MrRazamataz** [comment]
Ok so I know that the 1.16 version is still being worked on but I have found a few newer bugs that weren't mentioned (I don't think they were anyway).
There is only 1 version of items such as spawn eggs and fireworks (I don't know if this is meant by "Creative Menu doesn't show items with negative ids/have damage values. Eg. log:1)
I know this isn't the final release but I was gonna say that it is really laggy and I know its not my computer thats laggy.
I don't want to sound annoying I just want to help in any way that I can.

**Comment by RORIdev** [comment]
> There is only 1 version of items such as spawn eggs and fireworks (I don't know if this is meant by "Creative Menu doesn't show items with negative ids/have damage values. Eg. log:1)

About the spawn eggs, it could be caused by it. and that one is already fixed. idk about the fireworks tho.

**Comment by MrRazamataz** [comment]
Ok thank you. Where can download that version? Is there an way where I can download the latest version?

**Comment by RORIdev** [comment]
> Ok thank you. Where can download that version? Is there an way where I can download the latest version?

They should be available on the "Actions" tab.

**Comment by MrRazamataz** [comment]
Ah thank you.

**Comment by MrRazamataz** [comment]
Ok I downloaded a newer version and the lag has stopped! I dont know if its useful me telling you these things but skins dont work atm... Just tell me if you dont want be to say about these bugs because its not even been realised fully yet...

**Comment by MrRazamataz** [comment]
Well it lags less. It still freezes randomly and stuff. I noticed it when I went into creative and when someone died.

**Comment by RORIdev** [comment]
> 
> 
> Ok I downloaded a newer version and the lag has stopped! I dont know if its useful me telling you these things but skins dont work atm... Just tell me if you dont want be to say about these bugs because its not even been realised fully yet...

Don't worry, you can report these bugs as much as possible, this is **really** helpful! If we don't know them, we can't fix them so any report helps.

**Comment by MrRazamataz** [comment]
Ok, so its seems to randomly crash and the console becomes laggy and unable to run commands. The RAM usage reaches the max given to it and I have to stop the server and restart it using the X button or task manager. This seems to happen at random though I am trying to find out why its happens.
![ram usage crash](https://user-images.githubusercontent.com/56600481/85956459-f9219680-b97d-11ea-9f84-2eccef9931e0.png)

**Comment by MrRazamataz** [comment]
I think the issue is when a new player tries to join something about PowerNukkit messes with LuckPerms and causes the server to freeze up. It might not be this but it has happened multiple times and most (if not every) time a new player tried to join. If you want to join the server I have running PowerNukkit then let me know.

**Comment by joserobjr** [comment]
@MrRazamataz thank you for the reports, I really appreciate them and they are helpful.

I'm interesting in solving the performance issue that you are having but I need a few mechanical information.

Please run the command `/timings on`, let it enable for a few minutes, the performance might drop a little while it is enable since it's actively logging the timings of everything, it's also important that the big performance issue get caught by the timing (but don't let it die completely otherwise you won't be able to get the result). When you think it's ready, type `/timings paste`, you'll receive a link with the timings information, please share the link with us. The timings will keep running until you type `/timings off` or restart the server.

We also need the result of the `/debugpaste`  command, please execute it during the lag time. It will generate a link which contains the current configuration, recent log, thread dump and some useful tracing information, but it doesn't include timings, that's why the timings command is necessary.

The links are temporary and will expire I think in 30 days.

**Comment by MrRazamataz** [comment]
Ok. The commads might be hard to run during the lag as the server console fully freezes up and/or it takes ages to type a command. I will give it a try though.

**Comment by MrRazamataz** [comment]
@joserobjr 
Debug Paste Link: https://hastebin.com/vubizotena
Timings Link https://timings.aikar.co/?id=59339f5287f24911a861471c5f8a3450

**Comment by MrRazamataz** [comment]
Is there also a way to get fake inventorys working (https://ci.nukkitx.com/job/NukkitX/job/FakeInventories/job/master/ )?

**Comment by joserobjr** [comment]
@MrRazamataz Might be related to the new compression, your server seems to be taking a lot of timing compressing packets in the main thread. I'm going to see what I can do.

**Comment by tuilakhanh** [comment]
The enchanting table is broken in this version but anvil work normaly

**Comment by joserobjr** [comment]
Thank you, I added to the list

**Comment by tuilakhanh** [comment]
NukkitX#1518 (comment)

Scoreboards are not implemented in Nukkit, so this would have to be coming from a ScoreboardAPI plugin.

Closing this issue since it is plugin related.

**Comment by joserobjr** [comment]
Enchanting table packets (trying to enchant a diamond chestplate)
```java
0 = {InventoryTransactionPacket@6109} "InventoryTransactionPacket(transactionType=0, actions=[NetworkInventoryAction(sourceType=99999, windowId=-15, unknown=0, inventorySlot=0, oldItem=Item Air (0:0)x0, newItem=Item Diamond Chestplate (311:0)x1, stackNetworkId=0), NetworkInventoryAction(sourceType=99999, windowId=-17, unknown=0, inventorySlot=0, oldItem=Item Diamond Chestplate (311:0)x1 tags:0x0A0000090400656E63680A010000000203006C766C0100020200696400000000, newItem=Item Air (0:0)x0, stackNetworkId=0), NetworkInventoryAction(sourceType=0, windowId=124, unknown=0, inventorySlot=14, oldItem=Item Diamond Chestplate (311:0)x1, newItem=Item Diamond Chestplate (311:0)x1 tags:0x0A0000090400656E63680A010000000203006C766C0100020200696400000000, stackNetworkId=0)], transactionData=null, hasNetworkIds=false, legacyRequestId=0, isCraftingPart=false)"
1 = {PlayerActionPacket@6187} "PlayerActionPacket(entityId=8, action=20, x=0, y=0, z=0, face=1229200038)"
2 = {EntityEventPacket@6188} "EntityEventPacket(eid=8, event=34, data=-1)"
3 = {InventoryTransactionPacket@6189} "InventoryTransactionPacket(transactionType=0, actions=[NetworkInventoryAction(sourceType=99999, windowId=-16, unknown=0, inventorySlot=0, oldItem=Item Air (0:0)x0, newItem=Item Lapis Lazuli (351:4)x1, stackNetworkId=0), NetworkInventoryAction(sourceType=0, windowId=124, unknown=0, inventorySlot=15, oldItem=Item Lapis Lazuli (351:4)x1, newItem=Item Air (0:0)x0, stackNetworkId=0)], transactionData=null, hasNetworkIds=false, legacyRequestId=0, isCraftingPart=false)"
```
